@startuml
title OKRocket PersonalObjectiveUsecase オブジェクト図

left to right direction

skinparam object {
  BackgroundColor #ffffff
  BorderColor #7a7adb
  FontColor #000000
  BorderThickness 2
}

object "(ユーザー)" as User {
  名前 = "山田太郎"
  大学 = "山田大学"
  学部 = "情報学部"
  学年 = 3
  誕生日 =2022/01/01
}


frame "個人目標1" as ObjectiveFrame1 {
  object "(目標)" as Objective1 {
    タイトル = "英語を話せるようになる"
    説明 = "TOEICで800点を取る"
    開始日 = "2023-01-01"
    終了日 = "2023-12-31"
  }

  object "(個人振り返り)" as Reflection1 {
    タイトル = "英語力向上"
    説明 = "頑張ったことは...\nぶつかった壁は...\nどのように解決したか..."
  }

  object "(ガクチカ)" as Gakutika1 {
    タイトル = "英語力向上"
    説明 = "頑張ったことは...\nぶつかった壁は...\nどのように解決したか..."
  }

  object "(個人成果指標)" as KeyResult1 {
    説明 = 毎週100単語覚える
  }
}

frame "個人目標2" as ObjectiveFrame2 {
  object "(目標)" as Objective2 {
    タイトル = "英語を話せるようになる"
    説明 = "TOEICで800点を取る"
    開始日 = "2023-01-01"
    終了日 = "2023-12-31"
  }

  object "(個人振り返り)" as Reflection2 {
    タイトル = ""
    説明 = ""
  }

  object "(ガクチカ)" as Gakutika2 {
    タイトル = ""
    説明 = ""
  }

  object "(個人成果指標)" as KeyResult2 {
    説明 = 毎週100単語覚える
    開始日 = "2023-01-01"
    終了日 = "2023-12-31"
  }
}


object "(ステータス)" as Status {
  名前 = "進行中"
}
Status - KeyResult1 : includes >
note left of KeyResult1
  ステータスを管理: 未着手/進行中/完了/期限超過 (VO)
end note

Status - Objective1 : includes >
note right of Objective1
  成果指標タスクに合わせてステータス変化
  - 全て未着手 or 成果指標がない: 未着手
  - 1つ以上進行中: 進行中
  - 全て完了: 完了
end note

Objective1 -down- User
Objective2 -down- User

Objective1 "1" *-up- "*"  KeyResult1
Objective1 "1" o---"0..1" Reflection1
Objective1 "1" <..."0..1" Gakutika1 : uses <
note right of Gakutika1
  目標と振り返りからガクチカが生成される

  目標の終了期限が来たら作成はできるようにする
  ただし、振り返りがない場合は生成されない
end note

note right of Gakutika2
  [表示範囲]
  チームのガクチカである場合は、チームで共有
  個人のガクチカである場合は、個人で共有

  [生成条件]
  目標のステータスが"完了"になっていること 
  &&
  振り返りが全て埋まっていること

  [編集権限]
  チームにおいてはオリジナルのガクチカは、作成後に編集できない
  自分用にカスタマイズするために複製した場合は個人のアカウントで編集可能
  
  [削除権限]
  チームリーダーは、チームのガクチカを削除できる

end note

Objective2 "1" *-up- "*"  KeyResult2
Objective2 "1" o---"0..1" Reflection2
Objective2 "1" <..."0..1" Gakutika2 : uses <
note right of Gakutika2
  振り返りがない場合
  ガクチカは生成されない
end note

@enduml
