spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jooq:
    sql-dialect: H2
  flyway:
    locations: classpath:db/migration
    enabled: true
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
